### ISSUE TITLE
Observing a coding only supported above python 3.9

### ISSUE THREAD

**Issue by halfbottles** [Mantisus/dataquests_tag_modelling#1]
>    async def get_data(self, collection, filter_query, filter_fields):
                    current_filter_fields = {"_id": 0}
                    current_filter_fields |= filter_fields
in db_manager.py line 23，it is may only supported above python3.9.
Can u tell me which version of python u coding this project?

**Comment by Mantisus** [comment]
Hey, @halfbottles. 
I used 3.9.5 for this project. But it should work correctly with any version of python 3.8+.
Since the "|=" operator was added in Python 3.8
